name: app_center_ratings_client
description: Dart client for App Center Rating service
homepage: https://github.com/canonical/app_center_ratings_client.dart
repository: https://github.com/canonical/app_center_ratings_client.dart
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  fixnum: ^1.1.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  grpc: ^3.1.0
  meta: ^1.7.0
  protobuf: ^3.0.0
  protoc_plugin: ^21.0.1



dev_dependencies:
  build_runner: ^2.4.5
  lints: ^5.0.0
  mockito: ^5.4.2
  test: ^1.21.0
